version: '3.4'

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017